version: "3.7"
services:
  iatest:
    build: "./IATest"
    ports:
      - "4000:5000"

  iatestpanel:
    build: "./IATestPanel"
    ports:
      - "4001:5000"

  iatestbackend:
    build: "./IATestBackend"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/IATest
      - JWT_SECRET_KEY=6db7eebb64936ee54ff1669bb4311ca1f8779bf013864b6ef37d29bd347936de179187629d65b87efbcddc2fb3ac5ad31b8ec227f0319bb374fbf8dc49deee80131414f023eb26a6cfe15a8be9ef3f817242174be3ffe77323fb06d83fb94f2e49a4292c59f0e65f766c910ef9d01acafd01fb859a27a02abc4c461e83778582

  iatestpanelbackend:
    build: "./IATestPanelBackend"
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/IATest

  db:
    image: mongo
    ports:
      - "27017:27017"
